---
title: "Test_1"
author: "Kevin"
date: "4/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggmap)
library(maps)
library(leaflet)
library(readr)
library(dplyr)
library(rvest)
states <- map_data("state")
```

```{r}
url <- "https://inkplant.com/code/state-latitudes-longitudes"
state_center <- url %>%
  read_html() %>%
  html_node(xpath = '//*[@id="main_content_div"]/table') %>%
  html_table()

my_names <- state_center[1,]

colnames(state_center) <- my_names
state_center <- state_center %>%
  filter(State != "State")
```

```{r}
state_abb <- read_csv("Data/states.csv")
#state_abb <- state_abb %>%
#  mutate(State = tolower(State))
state_center <- left_join(state_center, state_abb, by = c("State" = "State"))
#all_counts <- all %>%
#  group_by(year, state) %>%
#  summarise(count = n())
state_center <- left_join(state_center, all, by = c("Abbreviation" = "state"))
state_center <- state_center %>%
  mutate(Longitude = as.numeric(Longitude), Latitude = as.numeric(Latitude))
leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~Longitude, lat = ~Latitude, data = state_center,
             label = ~as.character(State))


```



```{r}
library(geojson)
all_chlor <- all %>%
  filter(country == "USA") %>%
  group_by(year, state) %>%
  summarise(count = n())
all_chlor <- left_join(state_abb, all_chlor, by = c("Abbreviation" = "state"))
all_chlor <- mutate(all_chlor, State = tolower(State))
all_chlor_2001 <- all_chlor %>%
  filter(year == 2001)
chlor_2001 <- left_join(states, all_chlor_2001, by = c("region" = "State"))
chlor_2001 <- 
map_state <- map("state", region = ".", exact = TRUE, boundary = TRUE)
leaflet(map_state) %>%
  addTiles() %>%
  addPolygons(
    #fillColor = ~all_chlor_2001$count,
    color = "white",
    highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE))
  

```

```{r}

ggplotly(ggplot(data = participation) +
      geom_line(aes(x = year, y = men, group = 1, frame = year)))

```


