---
title: "Test_Boston"
author: "Kevin"
date: "4/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(tidyr)
results_2001 <- read_csv("Data/results_2001.csv")
results_2002 <- read_csv("Data/results_2002.csv")
results_2003 <- read_csv("Data/results_2003.csv")
results_2004 <- read_csv("Data/results_2004.csv")
results_2005 <- read_csv("Data/results_2005.csv")
results_2006 <- read_csv("Data/results_2006.csv")
results_2007 <- read_csv("Data/results_2007.csv")
results_2008 <- read_csv("Data/results_2008.csv")
results_2009 <- read_csv("Data/results_2009.csv")
results_2010 <- read_csv("Data/results_2010.csv")
results_2011 <- read_csv("Data/results_2011.csv")
results_2012 <- read_csv("Data/results_2012.csv")
results_2013 <- read_csv("Data/results_2013.csv")
results_2014 <- read_csv("Data/results_2014.csv")
results_2015 <- read_csv("Data/marathon_results_2015.csv")
results_2016 <- read_csv("Data/marathon_results_2016.csv")
results_2017 <- read_csv("Data/marathon_results_2017.csv")
all <- bind_rows(mutate(results_2001, year = "2001"), 
                 mutate(results_2002, year = "2002"),
                 mutate(results_2003, year = "2003"),
                 mutate(results_2004, year = "2004"),
                 mutate(results_2005, year = "2005"),
                 mutate(results_2006, year = "2006"),
                 mutate(results_2007, year = "2007"),
                 mutate(results_2008, year = "2008"),
                 mutate(results_2009, year = "2009"),
                 mutate(results_2010, year = "2010"),
                 mutate(results_2011, year = "2011"),
                 mutate(results_2012, year = "2012"))
  all <- all %>%
    select(age, gender, city, state, country, year)
  
  new <-bind_rows(
    (results_2013 %>%
      mutate(year = "2013") %>%
     select(age, gender, city, state, country, year)),
                 (results_2014 %>%
      mutate(year = "2014") %>%
     select(age, gender, city, state, country, year)),
                 (results_2015 %>%
      mutate(year = "2015") %>%
     select(age = Age, gender = "M/F", city = City, state = State, country = Country, year)),
                 (results_2016 %>%
      mutate(year = "2016") %>%
     select(age = Age, gender = "M/F", city = City, state = State, country = Country, year)),
                 (results_2017 %>%
      mutate(year = "2017") %>%
     select(age = Age, gender = "M/F", city = City, state = State, country = Country, year)))

all <- bind_rows(all, new)
colnames(all) <- c("Age", "Gender", "City", "State", "Country", "Year")

library(ggmap)
library(maps)
library(rvest)
states <- map_data("state")
state_abb <- read_csv("Data/states.csv")
state_abb <- state_abb %>%
  mutate(State = tolower(State))
states <- left_join(states, state_abb, by = c("region" = "State"))
all_counts <- all %>%
  mutate(age.range = ifelse(age %in% 18:34, "18-34", 
                            ifelse(age %in% 34:39, "34-39",
                                   ifelse(age %in% 40:44, "40-44",
                                          ifelse(age %in% 45:49, "45-49",
                                                 ifelse(age %in% 50:54, "50-54",
                                                        ifelse(age %in% 55:59, "55-59",
                                                               ifelse(age %in% 60:64, "60-64",
                                                                      ifelse(age %in% 65:69, "65-69",
                                                                             ifelse(age %in% 70:74, "70-74",
                                                                                    ifelse(age %in% 75:79, "75-79", "80+"))))))))))) %>%
  mutate(year = as.numeric(year)) %>%
  group_by(year, state, gender, age.range) %>%
  summarise(counts = n())
states <- inner_join(states, all_counts, by = c("Abbreviation" = "state"))

summary_1 <- all %>%
  group_by(year) %>%
  summarise(distinct_countries = n_distinct(country))
summary_2 <- all %>%
  group_by(year, gender) %>%
  summarise(count = n())
summary_2 <- spread(summary_2, 
                    key = gender, 
                    value = count)
summary <- left_join(summary_2, summary_1, by = c("year" = "year"))
summary <- mutate(summary, total = M + F)

country_counts <- all %>%
  group_by(year, country) %>%
  summarise(counts = n())

url <- "http://www.baa.org/races/boston-marathon/boston-marathon-history/participation.aspx"
tables <- url %>%
  read_html() %>%
  html_nodes(css = "table") 
participation <- html_table(tables[[2]])
colnames(participation) <- c("year", "total", "men", "women", "(F)_total", "(F)_men", "(F)_women")
```

```{r}
#shiny stuff
library(shiny)
library(dplyr)
library(ggplot2)
library(shinythemes)
server <- function(input, output) {
  output$line <- renderPlot({
    req(input$genderline)
    data_react <- select(participation, input$genderline, year) %>%
      filter(year <= input$animation)
    ggplot(data = data_react) +
      geom_line(aes_string(x = 'year', y = input$genderline, group = 1))
  })
  
  
  output$map <- renderPlot({
    states <- filter(states, gender %in% input$gender, age.range %in% input$age, year >= input$year[1], year <= input$year[2])
    ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, group = group, fill = log(counts)), color = "white") + 
  scale_fill_gradient(low = "#FFDD00", high = "#0004FF") +
  labs(fill = "Log of Runners") +
  coord_map() + 
  theme_void()
  })
  
  output$ustable <- DT::renderDataTable({
    states <- filter(states, gender %in% input$gender, age.range %in% input$age, year >= input$year[1], year <= input$year[2]) %>%
      select("State" = region, "Year" = year, "Gender" = gender, "Age Range" = age.range, "Number of Runners" = counts)
    DT::datatable(data = states, rownames = FALSE)
  })
  
  output$table <- DT::renderDataTable({
    req(input$vars)
    data_react <- select(all, input$vars)
    DT::datatable(data = data_react, rownames = FALSE)
  })
  
  output$summary <- DT::renderDataTable({
    req(input$sumyear)
    summ_react <- filter(summary, year %in% input$sumyear) %>%
      select("Year" = year, "Female" = "F", "Male" = "M", "Total Countries" = distinct_countries, "Number of Runners" = total)
    DT::datatable(data = summ_react, rownames = FALSE)
  })
}

  ui <- fluidPage(
    navbarPage("Boston Marathon", theme = shinythemes::shinytheme("united"),
    p("The", 
    tags$a(href="http://www.baa.org/", "Boston Marathon"), "has been around for 122 years. Each Patriots' Day, celebrated on the third Monday of April, thousands of runners from around the world come together and run 26.2 miles. Here we have data on the runners who have participated in the more recent Boston Marathons. Let's explore how the race has changed!"),
    tabsetPanel(type = "tabs",
                
                tabPanel(title = "Participation",
      sidebarLayout(
        
          sidebarPanel(
            helpText("Entries over the Years"),
                             
            radioButtons(inputId = "genderline",
                         label = "Which gender do you want to see?",
                         choices = list("Male" = "men",
                                        "Female" = "women",
                                        "Both" = "total"),
                        selected = ("total")),
            
            sliderInput(inputId = "animation", 
                        label = "Years:",
                        min = 1972, max = 2017,
                        value = 1972, step = 1,
                        animate = animationOptions(loop = TRUE),
                        sep = ""),
          tags$h5("Press play to begin!")),
      
      mainPanel(
        plotOutput(outputId = "line")
      )
      )),
      
                  tabPanel(title = "US Finishers",
    sidebarLayout(
      sidebarPanel(
        helpText("Boston Marathon finishers from the US"),
        
        checkboxGroupInput(inputId = "age",
                           label = "Which age range(s) do you want to see?",
                           choices = unique(states$age.range),
                           selected = c("18-34")),
        
        checkboxGroupInput(inputId = "gender",
                           label = "Which gender do you want to see?",
                           choices = unique(states$gender),
                           selected = c("M")),
      
      sliderInput(inputId = "year",
                    label = "Choose a range of years:",
                    min = 2001, max = 2017,
                    value = c(2015, 2017),
                    sep = "")
      ),
      
      mainPanel(
        tabsetPanel(
          tabPanel(
            title = "Map",
        plotOutput(outputId = "map")),
        tabPanel(
          title = "Data Table",
        DT::dataTableOutput(outputId = "ustable")
        )
      ) 
      ))),
                tabPanel(title = "All Finishers",
                         verticalLayout(
        helpText("We can also look at a table of all the finishers from all around the world."),
                 
        checkboxGroupInput(inputId = "vars",
                           label = "Which variable(s) do you want to see?",
                           choices = list("Age",
                                          "Gender",
                                          "City",
                                          "State",
                                          "Country",
                                          "Year"),
                           selected = c("Age", 
                                        "Gender",
                                        "City", 
                                        "State",
                                        "Country",
                                        "Year"))),
        
        DT::dataTableOutput(outputId = "table")
      ),
          tabPanel(title = "Summary",
                   sidebarLayout(
      
      sidebarPanel(
        helpText("What about some summary statistics from the last 16 years?"),
        
        checkboxGroupInput(inputId = "sumyear",
                           label = "Which year(s) do you want to see?",
                           choices = summary$year,
                           selected = summary$year)),
      mainPanel(
        DT::dataTableOutput(outputId = "summary")
      )
    )),
      tabPanel(title = "More Information",
               splitLayout(
                 helpText("The following are the links to the data we used for this app:"),
                 
                 p(tags$a(href="https://github.com/llimllib/bostonmarathon", "Data from 2001-2014"),
                  tags$a(href="https://www.kaggle.com/rojour/boston-results/data", "Data from 2015-2017"))
               ))
  ))
)
shinyApp(ui = ui, server = server)
#test
```

